version: "3"

services:
  web:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    container_name: nginx
    ports:
      - "82:80"
    links:
      - app
    networks:
      - app-network
  app:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    container_name: php-fpm
    ports:
      - 9000:9000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
